"""Byte-level chat format, model loading and streaming generation for the
OPERA chat model (experiments/build_chat_bytes.py, experiments/sft.py,
demo/app.py).

Format (raw UTF-8 bytes, ids = byte + BYTE_OFFSET; EOS = 2 ends every
assistant turn and stops generation):

    <|system|>\\n{text}\\n
    <|user|>\\n{text}\\n
    <|assistant|>\\n{text}<EOS>
"""
import codecs
import json
import os

import torch

from .reprs import BYTE_OFFSET, EOS, encode_bytes

ROLES = ('system', 'user', 'assistant')


def _turn(role, text):
    head = encode_bytes(f"<|{role}|>\n{text.strip()}")
    return head + ([EOS] if role == 'assistant' else encode_bytes("\n"))


def encode_conversation(messages, max_len):
    """messages: [{'role', 'content'}] -> (ids, was_cut). Keeps the longest
    prefix of whole turns that fits max_len and ends with an assistant
    turn; (None, False) if not even the first exchange fits."""
    ids, best, cut = [], None, False
    for m in messages:
        if m['role'] not in ROLES:
            continue
        t = _turn(m['role'], m['content'])
        if len(ids) + len(t) > max_len:
            cut = True
            break
        ids = ids + t
        if m['role'] == 'assistant':
            best = list(ids)
    if best is None:
        return None, False
    return best, cut or len(best) < len(ids)


def format_prompt(history, user_text, system=None, max_len=2048):
    """history: [(user, assistant), ...]. Returns prompt ids ending in
    '<|assistant|>\\n', keeping the most recent turns that fit max_len."""
    tail = _turn('user', user_text) + encode_bytes("<|assistant|>\n")
    turns = []
    for u, a in reversed(history):
        pair = _turn('user', u) + _turn('assistant', a)
        if len(pair) + len(tail) + sum(map(len, turns)) > max_len:
            break
        turns.insert(0, pair)
    sys_ids = _turn('system', system) if system else []
    if len(sys_ids) + len(tail) + sum(map(len, turns)) > max_len:
        sys_ids = []
    ids = sys_ids + [i for t in turns for i in t] + tail
    return ids[-max_len:]


def load_model(path_or_repo, device='cpu'):
    """Load an exported model (experiments/export_hf.py): a local folder or
    a Hugging Face model repo id holding config.json + model.safetensors."""
    from safetensors.torch import load_file
    from .model import OperaSpinorFenwickTree
    if os.path.isdir(path_or_repo):
        cfg_path = os.path.join(path_or_repo, 'config.json')
        w_path = os.path.join(path_or_repo, 'model.safetensors')
    else:
        from huggingface_hub import hf_hub_download
        cfg_path = hf_hub_download(path_or_repo, 'config.json')
        w_path = hf_hub_download(path_or_repo, 'model.safetensors')
    cfg = json.load(open(cfg_path))
    model = OperaSpinorFenwickTree(**cfg['model_kwargs'])
    model.load_state_dict(load_file(w_path), strict=True)
    return model.to(device).eval(), cfg


@torch.no_grad()
def stream_generate(model, prompt_ids, max_new=400, temperature=0.7,
                    top_p=0.9, seed=None):
    """Yield the decoded text so far after each generated byte; stops at
    EOS. Fenwick-incremental decoding: O(log T) compose nodes per byte."""
    from .incremental import OperaDecoder
    gen = torch.Generator().manual_seed(seed) if seed is not None else None
    dec = OperaDecoder(model)
    logits = None
    for t in prompt_ids:
        logits = dec.append(int(t))
    utf8 = codecs.getincrementaldecoder('utf-8')(errors='replace')
    text = ''
    for _ in range(max_new):
        lg = logits.float().cpu()                   # sample on CPU (any device)
        eos = lg[EOS].item()
        lg[:BYTE_OFFSET] = float('-inf')
        lg[EOS] = eos                               # EOS stays allowed
        if temperature <= 0:
            nxt = int(lg.argmax())
        else:
            probs = torch.softmax(lg / temperature, -1)
            sp, si = probs.sort(descending=True)
            keep = sp.cumsum(0) - sp < top_p
            sp = sp * keep
            nxt = int(si[torch.multinomial(sp / sp.sum(), 1, generator=gen)])
        if nxt == EOS:
            break
        text += utf8.decode(bytes([nxt - BYTE_OFFSET]))
        yield text
        logits = dec.append(nxt)
    text += utf8.decode(b'', final=True)
    yield text
